### ISSUE TITLE
Error in BindPayload

### ISSUE THREAD

**Issue by ItsTHEAvro** [ng1nX4O4/PatchApk#2]
Please delete the previous issue. Noobie here.
![Screenshot_Termux_20190828-120114](https://user-images.githubusercontent.com/42869374/63829543-a6590600-c98b-11e9-9575-c12b078d6c54.png)
Here is the error that it shows.
What to do?

**Comment by ng1nX4O4** [comment]
Bro Please Use Updated Version

Use This Step For Installation

```
rm -rf ~/PatchApk $PREFIX/bin/patchapk $PREFIX/java-fs $PREFIX/ubuntu
git clone https://github.com/ng1nX4O4/PatchApk/
cd PatchApk
bash setup
```
After Setup Try Again
This Will Install All Requirements
And Do It Fast

**Comment by ItsTHEAvro** [comment]
![Screenshot_Termux_20190828-121510](https://user-images.githubusercontent.com/42869374/63830246-875b7380-c98d-11e9-83d1-88b53e51e362.png)
Same problem.

**Comment by ng1nX4O4** [comment]
type this command

`apt show msfpatch`

**Comment by ng1nX4O4** [comment]
and then send screenshots

**Comment by ng1nX4O4** [comment]
Do It Fast I Don't Have Much Time

**Comment by ItsTHEAvro** [comment]
![Screenshot_Lawnchair_20190828-121746](https://user-images.githubusercontent.com/42869374/63830401-e02b0c00-c98d-11e9-825b-b636eb0aad28.png)

**Comment by ng1nX4O4** [comment]
now install msfpatch

`apt install msfpatch`
and then send screenshot

**Comment by ItsTHEAvro** [comment]
$ apt install msfpatch
Reading package lists... Done
Building dependency tree
Reading state information... Done
msfpatch is already the newest version (1.0).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

**Comment by ng1nX4O4** [comment]
Uninstall termux and install again for clean setup. And Around Of 500MB Required For Full Setup

**Comment by ItsTHEAvro** [comment]
Ok.Trying that

**Comment by ItsTHEAvro** [comment]
Ok, Trying that

**Comment by ng1nX4O4** [comment]
Please Give Me ScreenShots Of The Following Command
1. `apktool`
2. `signapk`
3. `java-fs whoami`
4. `java --version`

Do It First

**Comment by ItsTHEAvro** [comment]
$ apktool
proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/usr/java/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
$ signapk
proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"                                                     proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/usr/java/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
$ java-fs whoami
proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/usr/java/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
$ java --version
proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/usr/java/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
$

**Comment by ng1nX4O4** [comment]
Found The Error
use this command

`apt install java-fs --reinstall`
`apt install sigapk --reinstall`

Then Give Me A ScreenShot That Your Installation Is Complete

**Comment by ItsTHEAvro** [comment]
apt install java-fs --reinstall
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 3 not upgraded.
Need to get 1988 B of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://ng1nx4o4.github.io/termux-java termux/extras all java-fs all 1.0-1 [1988 B]
Fetched 1988 B in 0s (2695 B/s)
(Reading database ... 37037 files and directories currently installed.)
Preparing to unpack .../archives/java-fs_1.0-1_all.deb ...
Unpacking java-fs (1.0-1) over (1.0-1) ...
Setting up java-fs (1.0-1) ...
Downloading Extra Files
From External Server
Size: 35 MB
Please Wait............
Done

$ apt install signapk --reinstall
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 3 not upgraded.
Need to get 3544 B of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://ng1nx4o4.github.io/termux-java termux/extras all signapk all 1.0-1 [3544 B]
Fetched 3544 B in 0s (6097 B/s)
(Reading database ... 37037 files and directories currently installed.)
Preparing to unpack .../archives/signapk_1.0-1_all.deb ...
Unpacking signapk (1.0-1) over (1.0-1) ...
Setting up signapk (1.0-1) ...
Downloading Extra Files
From External Server
Size: 25MB
Please Wait............
proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/usr/java/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
Done

$

**Comment by ng1nX4O4** [comment]
Use This Commands And Try Again And give screenshots

```
rm -rf $PREFIX/ja*
apt install java-fs --reinstall
apt install sigapk --reinstall
```

**Comment by ItsTHEAvro** [comment]
Installation complete

**Comment by ng1nX4O4** [comment]
Give Output

apktool
signapk
java-fs whoami
java --version

**Comment by ng1nX4O4** [comment]
Do it fast

**Comment by ItsTHEAvro** [comment]
Sorry bro
Signapk installation process stuck on 66%

**Comment by ng1nX4O4** [comment]
Ok Wait It Will Take Time. Around 100mb will cost you

**Comment by ItsTHEAvro** [comment]
![Screenshot_Termux_20190828-130056](https://user-images.githubusercontent.com/42869374/63833070-eb813600-c993-11e9-826d-4628d1e85e8b.png)

**Comment by ng1nX4O4** [comment]
now time to install apktool
apt install apktool --reinstall

**Comment by ng1nX4O4** [comment]
after that try to bind.

**Comment by ng1nX4O4** [comment]
are you done.

Give screenshot of bind

**Comment by ItsTHEAvro** [comment]
![Screenshot_Termux_20190828-131309](https://user-images.githubusercontent.com/42869374/63833769-a78f3080-c995-11e9-8acb-86da54796f16.png)

**Comment by ItsTHEAvro** [comment]
For a moment, thought it worked!😞

**Comment by ng1nX4O4** [comment]
Use Another apk

**Comment by ng1nX4O4** [comment]
Use This One
https://m.apkpure.com/internet-speed-meter-lite/com.internet.speed.meter.lite/download?from=details

**Comment by ItsTHEAvro** [comment]
Trying....

**Comment by ng1nX4O4** [comment]
Okkk

**Comment by ng1nX4O4** [comment]
Closing This Issue

**Comment by ng1nX4O4** [comment]
Send ScreenShots Of Bind Apk

**Comment by ng1nX4O4** [comment]
My Bind
Successfull

![Screenshot_20190828-140040](https://user-images.githubusercontent.com/47913604/63836943-5f274100-c99c-11e9-8092-e98124cda984.png)

**Comment by ItsTHEAvro** [comment]
Worked this time
thanks a lot!

**Comment by ng1nX4O4** [comment]
Are You A Youtuber
