### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Isururanjana** [ng1nX4O4/PatchApk#3]
![Screenshot_2019-08-29-12-32-30](https://user-images.githubusercontent.com/54226767/63918091-a1628800-ca59-11e9-94a7-f0d5449fa590.png)
Whats wrong sir?

**Comment by ng1nX4O4** [comment]
Use This Command And TryAgain
```
rm -rf $PREFIX/ja*
apt install java-fs --reinstall
apt install sigapk --reinstall
apt install apktool --reinstall
```

**Comment by ng1nX4O4** [comment]
Contact Me On Whatsapp
Whatsapp No. +8801734470201

**Comment by ng1nX4O4** [comment]
Closing This Issue
Duplicate of #2
